name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dokku deploy
        uses: dokku/github-action@v1
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/${{ secrets.DOKKU_APP_NAME }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

      - name: Enable Letsencrypt
        uses: dokku/ssh-command-action@v1
        with:
          host: ${{ secrets.DOKKU_HOST }}
          private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          command: |
            dokku letsencrypt:enable ${{ secrets.DOKKU_APP_NAME }}
            dokku letsencrypt:cron-job --add
